// <auto-generated />
using System;
using CompanyManagement.API.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompanyManagement.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231101053853_dataDraft")]
    partial class dataDraft
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompanyManagement.API.Models.AuthUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("'00000000-0000-0000-0000-000000000000'");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid?>("UpdatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("'00000000-0000-0000-0000-000000000000'");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a61c0906-b308-4f6e-b860-28f4e3ee8713"),
                            CreatedAt = new DateTime(2023, 11, 1, 10, 38, 52, 934, DateTimeKind.Local).AddTicks(1678),
                            CreatedBy = new Guid("442a71be-cef4-4dfc-9d3b-1b2bd29556b7"),
                            Email = "faisal@gmail.com",
                            FirstName = "Faisal",
                            LastName = "Shahzad",
                            Password = "Faisal@123",
                            Salt = "LKDJ03230"
                        },
                        new
                        {
                            Id = new Guid("d0413c86-36c6-486b-982d-b13fa76b90b9"),
                            CreatedAt = new DateTime(2023, 11, 1, 10, 38, 52, 934, DateTimeKind.Local).AddTicks(1708),
                            CreatedBy = new Guid("d8c1f3a8-abb1-4b95-b809-63aa61490d8e"),
                            Email = "tuan@gmail.com",
                            FirstName = "Le",
                            LastName = "Tuan",
                            Password = "Faisal@123",
                            Salt = "LKDJ03230"
                        },
                        new
                        {
                            Id = new Guid("cfae8354-c7f7-4bd7-af31-43fa991b078e"),
                            CreatedAt = new DateTime(2023, 11, 1, 10, 38, 52, 934, DateTimeKind.Local).AddTicks(1712),
                            CreatedBy = new Guid("5984c1e3-1edb-49f8-abbc-e695bd6c8ad6"),
                            Email = "marc@gmail.com",
                            FirstName = "Marc",
                            LastName = "Josha",
                            Password = "Faisal@123",
                            Salt = "LKDJ03230"
                        });
                });

            modelBuilder.Entity("CompanyManagement.API.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CompanyLevel")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CompanyNo")
                        .HasColumnType("int")
                        .HasAnnotation("MinValue", 1);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("'00000000-0000-0000-0000-000000000000'");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NumberOfEmployees")
                        .HasColumnType("int");

                    b.Property<Guid?>("ParentCompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid?>("UpdatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("'00000000-0000-0000-0000-000000000000'");

                    b.HasKey("Id");

                    b.HasIndex("ParentCompanyId");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("531fd700-37c7-47d6-9055-8474f62be903"),
                            City = "Kuala Lumpur",
                            CompanyLevel = 0,
                            CompanyName = "Company1",
                            CompanyNo = 1,
                            CreatedAt = new DateTime(2023, 11, 1, 10, 38, 52, 934, DateTimeKind.Local).AddTicks(1899),
                            CreatedBy = new Guid("354b08da-1709-4817-9521-b43fa0947e14"),
                            Industry = "ITServices",
                            NumberOfEmployees = 10
                        },
                        new
                        {
                            Id = new Guid("39b62d5b-1cb9-476f-9fd3-f67ee3c55436"),
                            City = "Kuala Lumpur",
                            CompanyLevel = 0,
                            CompanyName = "Company2",
                            CompanyNo = 2,
                            CreatedAt = new DateTime(2023, 11, 1, 10, 38, 52, 934, DateTimeKind.Local).AddTicks(1915),
                            CreatedBy = new Guid("79807b6b-d106-4bde-97ca-bce4feaa2282"),
                            Industry = "ITServices",
                            NumberOfEmployees = 55
                        },
                        new
                        {
                            Id = new Guid("dad85e0f-be78-4537-b5a4-e74f747aec46"),
                            City = "Kuala Lumpur",
                            CompanyLevel = 0,
                            CompanyName = "Company3",
                            CompanyNo = 3,
                            CreatedAt = new DateTime(2023, 11, 1, 10, 38, 52, 934, DateTimeKind.Local).AddTicks(1922),
                            CreatedBy = new Guid("648ccfcd-309c-4dfc-9d61-bf1f331f7540"),
                            Industry = "ITServices",
                            NumberOfEmployees = 150
                        },
                        new
                        {
                            Id = new Guid("edbc63e3-fa4b-47d0-a1d6-5e5d5f4f1913"),
                            City = "Kuala Lumpur",
                            CompanyLevel = 0,
                            CompanyName = "Company4",
                            CompanyNo = 4,
                            CreatedAt = new DateTime(2023, 11, 1, 10, 38, 52, 934, DateTimeKind.Local).AddTicks(1926),
                            CreatedBy = new Guid("062ed847-3047-4266-a2fb-999aa09d9e9b"),
                            Industry = "ITServices",
                            NumberOfEmployees = 30
                        },
                        new
                        {
                            Id = new Guid("3eb8eb70-7c11-4fe9-b3c5-98c79219ace7"),
                            City = "Kuala Lumpur",
                            CompanyLevel = 0,
                            CompanyName = "Company5",
                            CompanyNo = 5,
                            CreatedAt = new DateTime(2023, 11, 1, 10, 38, 52, 934, DateTimeKind.Local).AddTicks(1930),
                            CreatedBy = new Guid("6a2fa70f-8363-4087-9191-d0ea9c7647a9"),
                            Industry = "ITServices",
                            NumberOfEmployees = 100
                        },
                        new
                        {
                            Id = new Guid("e10b7c92-75a1-45ea-932e-8804e48a9140"),
                            City = "Kuala Lumpur",
                            CompanyLevel = 0,
                            CompanyName = "Company6",
                            CompanyNo = 6,
                            CreatedAt = new DateTime(2023, 11, 1, 10, 38, 52, 934, DateTimeKind.Local).AddTicks(1933),
                            CreatedBy = new Guid("d27ccd89-7763-4798-a351-b95911831b5b"),
                            Industry = "ITServices",
                            NumberOfEmployees = 10
                        },
                        new
                        {
                            Id = new Guid("4a96c358-87e4-4e3f-9cfa-9d22dfe2e557"),
                            City = "Kuala Lumpur",
                            CompanyLevel = 0,
                            CompanyName = "Company7",
                            CompanyNo = 7,
                            CreatedAt = new DateTime(2023, 11, 1, 10, 38, 52, 934, DateTimeKind.Local).AddTicks(1939),
                            CreatedBy = new Guid("3c7c975b-1162-49cc-b126-43840164939c"),
                            Industry = "ITServices",
                            NumberOfEmployees = 40
                        },
                        new
                        {
                            Id = new Guid("ef4cd96e-90fd-4e59-8fcd-f7421db8606d"),
                            City = "Kuala Lumpur",
                            CompanyLevel = 0,
                            CompanyName = "Company8",
                            CompanyNo = 8,
                            CreatedAt = new DateTime(2023, 11, 1, 10, 38, 52, 934, DateTimeKind.Local).AddTicks(1943),
                            CreatedBy = new Guid("27ebaff4-c17c-4d1b-8d10-885b2d4a2f32"),
                            Industry = "ITServices",
                            NumberOfEmployees = 10
                        },
                        new
                        {
                            Id = new Guid("3e768c9d-cea6-4f4c-b729-1aafd9ae778e"),
                            City = "Kuala Lumpur",
                            CompanyLevel = 0,
                            CompanyName = "Company9",
                            CompanyNo = 9,
                            CreatedAt = new DateTime(2023, 11, 1, 10, 38, 52, 934, DateTimeKind.Local).AddTicks(1947),
                            CreatedBy = new Guid("3d72d29a-7e25-4644-a93e-ad649b8f21f7"),
                            Industry = "ITServices",
                            NumberOfEmployees = 300
                        },
                        new
                        {
                            Id = new Guid("dbd62898-0e2c-424d-9d48-42096eaad2e2"),
                            City = "Kuala Lumpur",
                            CompanyLevel = 0,
                            CompanyName = "Company10",
                            CompanyNo = 10,
                            CreatedAt = new DateTime(2023, 11, 1, 10, 38, 52, 934, DateTimeKind.Local).AddTicks(1950),
                            CreatedBy = new Guid("26d4095b-de64-4090-b1a0-c971728ccf08"),
                            Industry = "ITServices",
                            NumberOfEmployees = 500
                        },
                        new
                        {
                            Id = new Guid("543eccbb-006c-4e16-9b54-ff5c36e6fe9d"),
                            City = "Kuala Lumpur",
                            CompanyLevel = 0,
                            CompanyName = "Company11",
                            CompanyNo = 11,
                            CreatedAt = new DateTime(2023, 11, 1, 10, 38, 52, 934, DateTimeKind.Local).AddTicks(1956),
                            CreatedBy = new Guid("cba7ec11-c4c8-4ddd-81a5-e5d3c2df4229"),
                            Industry = "ITServices",
                            NumberOfEmployees = 770
                        },
                        new
                        {
                            Id = new Guid("c7311dec-bfa8-4ca2-a897-e5e2e100187d"),
                            City = "Kuala Lumpur",
                            CompanyLevel = 0,
                            CompanyName = "Company12",
                            CompanyNo = 12,
                            CreatedAt = new DateTime(2023, 11, 1, 10, 38, 52, 934, DateTimeKind.Local).AddTicks(1960),
                            CreatedBy = new Guid("c40b842c-291e-4ff5-b7d9-2b98eb050d90"),
                            Industry = "ITServices",
                            NumberOfEmployees = 1200
                        },
                        new
                        {
                            Id = new Guid("6727acc2-d544-48d5-ab81-73a214204202"),
                            City = "Kuala Lumpur",
                            CompanyLevel = 0,
                            CompanyName = "Company13",
                            CompanyNo = 13,
                            CreatedAt = new DateTime(2023, 11, 1, 10, 38, 52, 934, DateTimeKind.Local).AddTicks(1963),
                            CreatedBy = new Guid("dc27e925-c694-48fe-9f77-daecc2436298"),
                            Industry = "ITServices",
                            NumberOfEmployees = 600
                        },
                        new
                        {
                            Id = new Guid("5da087f3-9e65-4009-8ab7-e404f927bbbe"),
                            City = "Kuala Lumpur",
                            CompanyLevel = 0,
                            CompanyName = "Company14",
                            CompanyNo = 14,
                            CreatedAt = new DateTime(2023, 11, 1, 10, 38, 52, 934, DateTimeKind.Local).AddTicks(1967),
                            CreatedBy = new Guid("0d60efe5-5b3b-4cf7-b0b2-d91ce156be11"),
                            Industry = "ITServices",
                            NumberOfEmployees = 3000
                        },
                        new
                        {
                            Id = new Guid("591cfc26-5a7f-4927-a658-f211530d6f0d"),
                            City = "Kuala Lumpur",
                            CompanyLevel = 0,
                            CompanyName = "Company15",
                            CompanyNo = 15,
                            CreatedAt = new DateTime(2023, 11, 1, 10, 38, 52, 934, DateTimeKind.Local).AddTicks(1973),
                            CreatedBy = new Guid("c5e7715f-37f0-443c-9b26-9c0700abd434"),
                            Industry = "ITServices",
                            NumberOfEmployees = 550
                        },
                        new
                        {
                            Id = new Guid("5f074a61-c8e4-4bfe-b02e-4cac4741b51b"),
                            City = "Kuala Lumpur",
                            CompanyLevel = 1,
                            CompanyName = "Company16",
                            CompanyNo = 16,
                            CreatedAt = new DateTime(2023, 11, 1, 10, 38, 52, 934, DateTimeKind.Local).AddTicks(1976),
                            CreatedBy = new Guid("ede51c1f-6a99-4845-a8b2-a93e0b3ed177"),
                            Industry = "ITServices",
                            NumberOfEmployees = 350
                        },
                        new
                        {
                            Id = new Guid("a2503cf6-812c-49d8-95bc-3d95d49af19e"),
                            City = "Kuala Lumpur",
                            CompanyLevel = 1,
                            CompanyName = "Company17",
                            CompanyNo = 17,
                            CreatedAt = new DateTime(2023, 11, 1, 10, 38, 52, 934, DateTimeKind.Local).AddTicks(1980),
                            CreatedBy = new Guid("3e677607-956d-4334-9dbb-cc15944becc7"),
                            Industry = "ITServices",
                            NumberOfEmployees = 10
                        },
                        new
                        {
                            Id = new Guid("ae32f26c-dd6d-4360-aad4-a76c99bd7234"),
                            City = "Kuala Lumpur",
                            CompanyLevel = 1,
                            CompanyName = "Company18",
                            CompanyNo = 18,
                            CreatedAt = new DateTime(2023, 11, 1, 10, 38, 52, 934, DateTimeKind.Local).AddTicks(1984),
                            CreatedBy = new Guid("d476f4ce-0249-4ad3-a2b4-f3fd99081b6b"),
                            Industry = "ITServices",
                            NumberOfEmployees = 10
                        },
                        new
                        {
                            Id = new Guid("050138b6-6c23-4346-88db-87fb74bfcb44"),
                            City = "Kuala Lumpur",
                            CompanyLevel = 1,
                            CompanyName = "Company19",
                            CompanyNo = 19,
                            CreatedAt = new DateTime(2023, 11, 1, 10, 38, 52, 934, DateTimeKind.Local).AddTicks(1989),
                            CreatedBy = new Guid("9c967858-7a9d-4d62-bdec-f9aee4c02f1e"),
                            Industry = "ITServices",
                            NumberOfEmployees = 100
                        },
                        new
                        {
                            Id = new Guid("3a80ed4e-5724-4799-a5df-cf3a2ab819a4"),
                            City = "Kuala Lumpur",
                            CompanyLevel = 1,
                            CompanyName = "Company20",
                            CompanyNo = 20,
                            CreatedAt = new DateTime(2023, 11, 1, 10, 38, 52, 934, DateTimeKind.Local).AddTicks(1993),
                            CreatedBy = new Guid("2ab8e010-8e02-4550-ba0d-66833a8f4920"),
                            Industry = "ITServices",
                            NumberOfEmployees = 270
                        },
                        new
                        {
                            Id = new Guid("ce0fe173-d0b7-4aae-a26a-604b67848995"),
                            City = "Kuala Lumpur",
                            CompanyLevel = 1,
                            CompanyName = "Company21",
                            CompanyNo = 21,
                            CreatedAt = new DateTime(2023, 11, 1, 10, 38, 52, 934, DateTimeKind.Local).AddTicks(1997),
                            CreatedBy = new Guid("9d8fcdf6-3ef0-48d9-a9cc-c77c9d245881"),
                            Industry = "ITServices",
                            NumberOfEmployees = 10
                        },
                        new
                        {
                            Id = new Guid("3dca1e9c-df90-4b41-850e-1231ae301ec4"),
                            City = "Kuala Lumpur",
                            CompanyLevel = 1,
                            CompanyName = "Company22",
                            CompanyNo = 22,
                            CreatedAt = new DateTime(2023, 11, 1, 10, 38, 52, 934, DateTimeKind.Local).AddTicks(2000),
                            CreatedBy = new Guid("d30b0493-117d-4e2c-8765-80574f96658d"),
                            Industry = "ITServices",
                            NumberOfEmployees = 10
                        },
                        new
                        {
                            Id = new Guid("83a5bcbe-6d6e-4847-92fb-e0f966abd05c"),
                            City = "Kuala Lumpur",
                            CompanyLevel = 1,
                            CompanyName = "Company23",
                            CompanyNo = 23,
                            CreatedAt = new DateTime(2023, 11, 1, 10, 38, 52, 934, DateTimeKind.Local).AddTicks(2006),
                            CreatedBy = new Guid("40e68e3f-e41f-443a-a215-1f0559d33130"),
                            Industry = "ITServices",
                            NumberOfEmployees = 10
                        },
                        new
                        {
                            Id = new Guid("8af1da6b-2cdb-455f-b37d-496e450e0258"),
                            City = "Kuala Lumpur",
                            CompanyLevel = 1,
                            CompanyName = "Company24",
                            CompanyNo = 24,
                            CreatedAt = new DateTime(2023, 11, 1, 10, 38, 52, 934, DateTimeKind.Local).AddTicks(2010),
                            CreatedBy = new Guid("fcfc113a-6316-490d-abd3-18d6e8b09fa7"),
                            Industry = "ITServices",
                            NumberOfEmployees = 50
                        },
                        new
                        {
                            Id = new Guid("ce3d59ff-4499-4d85-af44-e1b4f78df3f1"),
                            City = "Kuala Lumpur",
                            CompanyLevel = 1,
                            CompanyName = "Company25",
                            CompanyNo = 25,
                            CreatedAt = new DateTime(2023, 11, 1, 10, 38, 52, 934, DateTimeKind.Local).AddTicks(2013),
                            CreatedBy = new Guid("03931597-82cc-4187-93fe-7e869a12e80b"),
                            Industry = "ITServices",
                            NumberOfEmployees = 10
                        },
                        new
                        {
                            Id = new Guid("6548679a-d29c-477f-9958-1e982d221515"),
                            City = "Kuala Lumpur",
                            CompanyLevel = 1,
                            CompanyName = "Company26",
                            CompanyNo = 26,
                            CreatedAt = new DateTime(2023, 11, 1, 10, 38, 52, 934, DateTimeKind.Local).AddTicks(2017),
                            CreatedBy = new Guid("cec76c4a-3bab-4868-ae89-11943fffdb25"),
                            Industry = "ITServices",
                            NumberOfEmployees = 60
                        },
                        new
                        {
                            Id = new Guid("d9091216-c339-4cfd-805f-75b9eefa8603"),
                            City = "Kuala Lumpur",
                            CompanyLevel = 2,
                            CompanyName = "Company27",
                            CompanyNo = 27,
                            CreatedAt = new DateTime(2023, 11, 1, 10, 38, 52, 934, DateTimeKind.Local).AddTicks(2023),
                            CreatedBy = new Guid("e3412ad8-a39d-4fb1-9ad3-0cdd47fcf9ed"),
                            Industry = "ITServices",
                            NumberOfEmployees = 80
                        },
                        new
                        {
                            Id = new Guid("5474783e-3bda-45fd-ac4f-74fc99656259"),
                            City = "Kuala Lumpur",
                            CompanyLevel = 2,
                            CompanyName = "Company28",
                            CompanyNo = 28,
                            CreatedAt = new DateTime(2023, 11, 1, 10, 38, 52, 934, DateTimeKind.Local).AddTicks(2027),
                            CreatedBy = new Guid("8ef6f4c4-8a1c-46c9-9077-85a58c6962ed"),
                            Industry = "ITServices",
                            NumberOfEmployees = 10
                        },
                        new
                        {
                            Id = new Guid("b61c1a5b-7ac5-453d-9fe0-6d2193df89df"),
                            City = "Kuala Lumpur",
                            CompanyLevel = 2,
                            CompanyName = "Company29",
                            CompanyNo = 29,
                            CreatedAt = new DateTime(2023, 11, 1, 10, 38, 52, 934, DateTimeKind.Local).AddTicks(2030),
                            CreatedBy = new Guid("4e24250c-9ca1-4cd4-876d-49de4c344bde"),
                            Industry = "ITServices",
                            NumberOfEmployees = 10
                        },
                        new
                        {
                            Id = new Guid("3a716e09-c8d9-4e53-8206-2fcc2083927f"),
                            City = "Kuala Lumpur",
                            CompanyLevel = 2,
                            CompanyName = "Company30",
                            CompanyNo = 30,
                            CreatedAt = new DateTime(2023, 11, 1, 10, 38, 52, 934, DateTimeKind.Local).AddTicks(2034),
                            CreatedBy = new Guid("694b58df-23f2-4cba-b852-0b7b9a2c717f"),
                            Industry = "ITServices",
                            NumberOfEmployees = 10
                        });
                });

            modelBuilder.Entity("CompanyManagement.API.Models.Company", b =>
                {
                    b.HasOne("CompanyManagement.API.Models.Company", "ParentCompany")
                        .WithMany()
                        .HasForeignKey("ParentCompanyId");

                    b.Navigation("ParentCompany");
                });
#pragma warning restore 612, 618
        }
    }
}
